// MyMoney.Web/FrontEnd/apps/mymoney-react/src/app/pages/budgets/index.tsx
import { Link } from 'react-router-dom';
import { ChangeEventHandler, useEffect, useState } from 'react';
import { useDispatch } from 'react-redux';
import { useSelector } from 'react-redux';
import InlineInput from '../../components/inline-input';
import BasicBudgetButtons from '../../components/basic-budget-buttons';
import { maxValidator, minValidator, requiredValidator } from '../../functions/validators';
import { deleteBudget, fetchBudgets, refreshBudgets, selectBudgetState, setSelectedMonth } from '../../state/budgets-slice';
import { AsyncStatus, IBudgetState } from '../../state/types';
import { useValidatedState } from '../../hooks/validation';

export default function Budgets() {
   const budgetState: IBudgetState = useSelector(selectBudgetState);
   const dispatch = useDispatch<any>();
   const [yearState, setYearState] = useValidatedState<number>(2020, [
      requiredValidator('Start is required'),
      minValidator(1980, 'Year must be greater than or equal to 1980'),
   ]);
   const [monthState, setMonthState] = useValidatedState<number>(1, [
      requiredValidator('Start is required'),
      maxValidator(12, 'Month must be less than or equal to 12'),
      minValidator(1, 'Month must be greater than or equal to 1'),
   ]);

   useEffect(() => {
      setYearState(budgetState.searchParameters.year);
      setMonthState(budgetState.searchParameters.month);
   }, [dispatch]);

   const loading = budgetState.budgets.status === AsyncStatus.loading;

   useEffect(() => {
      if (loading || (!loading && !budgetState.searchParameters.refresh)) {
         return;
      }

      dispatch(
         fetchBudgets({
            search: {
               year: budgetState.searchParameters.year,
               month: budgetState.searchParameters.month,
            },
         })
      );
   }, [budgetState]);

   const updateYear: ChangeEventHandler<HTMLInputElement> = (event) => {
      const year: number = Number.parseInt(event.target.value);
      setYearState(year);
      dispatch(setSelectedMonth(year, monthState.value));
   };

   const updateMonth: ChangeEventHandler<HTMLInputElement> = (event) => {
      let month: number = Number.parseInt(event.target.value);

      if (month === 13 && monthState.value === 12) {
         // Loop back to january
         month = 1;
         event.currentTarget.value = '1';
      }

      if (month === 0 && monthState.value === 1) {
         // Loop back to december
         month = 12;
         event.currentTarget.value = '12';
      }

      setMonthState(month);
      dispatch(setSelectedMonth(yearState.value, month));
   };

   const refershClicked = () => {
      if (loading) {
         return;
      }

      const yearErrors = setYearState(yearState.value);
      const monthErrors = setMonthState(monthState.value);

      if (yearErrors || monthErrors) {
         return;
      }

      dispatch(refreshBudgets());
   };

   const onDeleteBudgetClicked = (budgetId: number) => {
      dispatch(deleteBudget({ budgetId }));
   };

   const rows = [];

   for (const budget of budgetState.budgets.data) {
      rows.push(
         <tr key={budget.id}>
            <td>{budget.name}</td>
            <td>{budget.amount}</td>
            <td className={budget.remaining <= 0 ? 'text-danger' : ''}>{budget.remaining}</td>
            <td>{budget.notes}</td>
            <td className="pull-right">
               <BasicBudgetButtons budget={budget} onDeleteClicked={() => onDeleteBudgetClicked(budget.id)} />
            </td>
         </tr>
      );
   }

   return (
      <>
         <h2>Budgets</h2>
         <div className="form-inline">
            <InlineInput
               name="year"
               labelText="Year"
               showErrors={true}
               onChange={updateYear}
               defaultValue={`${yearState.value}`}
               errors={yearState.errors}
               type="number"
            />
            <InlineInput
               name="month"
               labelText="Month"
               showErrors={true}
               onChange={updateMonth}
               defaultValue={`${monthState.value}`}
               errors={monthState.errors}
               type="number"
            />

            <div className="input-group mb-3 pr-2 btn-group">
               <button
                  disabled={loading}
                  type="button"
                  onClick={refershClicked}
                  className="btn btn-primary material-icons"
                  data-toggle="tooltip"
                  data-placement="bottom"
                  title="Refresh budgets"
               >
                  {loading ? <span className="spinner-border spinner-border-sm"></span> : <div className="spin">refresh</div>}
               </button>
               <Link
                  className="btn btn-success material-icons"
                  to="/budgets/add"
                  data-toggle="tooltip"
                  data-placement="bottom"
                  title="Add new budget"
               >
                  add
               </Link>
            </div>
         </div>
         <div className="container-fluid">
            <table className="table">
               <thead>
                  <tr>
                     <th scope="col">Name</th>
                     <th scope="col">Amount</th>
                     <th scope="col">Remaining</th>
                     <th scope="col">Notes</th>
                     <th scope="col"></th>
                  </tr>
               </thead>
               <tbody>{rows}</tbody>
            </table>
         </div>
      </>
   );
}

// MyMoney.Web/FrontEnd/apps/mymoney-angular/src/app/pages/budgets/budgets.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { BudgetViewModel } from '@mymoney/common';
import { BudgetService } from '../../shared/services';
import { Store } from '@ngrx/store';
import { IAppState } from '../../shared/state/app-state';
import { selectBudgets, selectBudgetsSearchParameters } from '../../shared/state/selectors/budget.selector';
import { monthValidator } from '../../shared/common-validators';

@Component({
   templateUrl: './budgets.component.html',
   styleUrls: ['./budgets.component.scss']
})
export class BudgetsComponent implements OnInit {

   public budgets: BudgetViewModel[] = [];
   public monthIdForm: FormGroup;
   public monthIdFormControls = {
      year: new FormControl(0, [Validators.required, Validators.min(1980)]),
      month: new FormControl(0, [Validators.required, monthValidator])
   };
   public loading = false;
   public submitted = false;

   constructor(
      private readonly budgetService: BudgetService,
      private readonly store: Store<IAppState>
   ) {
      this.monthIdForm = new FormGroup(this.monthIdFormControls);
   }

   public ngOnInit(): void {
      this.store
         .select(selectBudgets)
         .subscribe((budgets) => {
            this.budgets = budgets.map(b => new BudgetViewModel(b));
            this.loading = false;
         });

      this.store
         .select(selectBudgetsSearchParameters)
         .subscribe((searchParams) => {
            const month = searchParams.month;
            const year = searchParams.year;

            this.monthIdFormControls.year.setValue(year);
            this.monthIdFormControls.month.setValue(month);
         });

      this.budgetService.refreshBudgets();
   }

   public updateBudgets(): void {
      this.submitted = true;

      if (this.monthIdForm.invalid) {
         return;
      }

      const year = this.monthIdFormControls.year.value as number;
      const month = this.monthIdFormControls.month.value as number;

      this.loading = true;

      this.budgetService.updateMonthId(month, year);
   }

   public deleteBudget(id: number): void {
      if (!confirm(`Delete budget ${id}?`)) {
         return;
      }

      this.budgetService.deleteBudget(id);
   }
}

<h2>Budgets</h2>
<form [formGroup]="monthIdForm" (ngSubmit)="updateBudgets()">
   <div class="form-inline">
      <div class="input-group mb-3 pr-2">
         <div class="input-group-prepend">
            <span class="input-group-text">Year</span>
         </div>
         <input
            type="number"
            formControlName="year"
            class="form-control"
            [ngClass]="{
               'is-invalid': submitted && monthIdFormControls.year.errors
            }"
            (change)="updateBudgets()"
         />
         <div
            *ngIf="submitted && monthIdFormControls.year.errors"
            class="invalid-feedback"
         >
            <div *ngIf="monthIdFormControls.year.errors['required']">
               Year is required
            </div>
            <div *ngIf="monthIdFormControls.year.errors['min']">
               Year cannot be less than 1980
            </div>
         </div>
      </div>
      <div class="input-group mb-3 pr-2">
         <div class="input-group-prepend">
            <span class="input-group-text">Month</span>
         </div>
         <input
            type="number"
            formControlName="month"
            class="form-control"
            [ngClass]="{
               'is-invalid': submitted && monthIdFormControls.month.errors
            }"
            (change)="updateBudgets()"
         />
         <div
            *ngIf="submitted && monthIdFormControls.month.errors"
            class="invalid-feedback"
         >
            <div *ngIf="monthIdFormControls.month.errors['required']">
               Month is required
            </div>
            <div *ngIf="monthIdFormControls.month.errors['invalidMonth']">
               Month must be 1 - 12
            </div>
         </div>
      </div>
      <div class="input-group mb-3 pr-2 btn-group">
         <button
            [disabled]="loading"
            class="btn btn-primary material-icons"
            data-toggle="tooltip"
            data-placement="bottom"
            title="Refresh budgets"
         >
            <span
               *ngIf="loading"
               class="spinner-border spinner-border-sm"
            ></span>
            <div *ngIf="!loading" class="spin">refresh</div>
         </button>
         <a
            class="btn btn-success material-icons"
            routerLink="./add"
            data-toggle="tooltip"
            data-placement="bottom"
            title="Add new budget"
         >
            add
         </a>
      </div>
   </div>
</form>
<div class="container-fluid">
   <table class="table">
      <thead>
         <tr>
            <th scope="col">Name</th>
            <th scope="col">Amount</th>
            <th scope="col">Remaining</th>
            <th scope="col">Notes</th>
            <th scope="col"></th>
         </tr>
      </thead>
      <tbody>
         <tr *ngFor="let budget of budgets; let i = index">
            <td>{{ budget.name }}</td>
            <td>{{ budget.amount }}</td>
            <td [ngClass]="{ 'text-danger': budget.showWarning }">
               {{ budget.remaining }}
            </td>
            <td>{{ budget.notes }}</td>
            <td class="pull-right">
               <mymoney-budget-buttons
                  [budget]="budget"
                  (deleteBudget)="deleteBudget(budget.id)"
               ></mymoney-budget-buttons>
            </td>
         </tr>
      </tbody>
   </table>
</div>
