// MyMoney.Web/FrontEnd/apps/mymoney-react/src/app/components/chart.tsx
import { IChartDataProvider } from '../interfaces/chart-data-provider';
import {
   LineChart,
   Line,
   XAxis,
   YAxis,
   CartesianGrid,
   Tooltip,
   Legend,
   ResponsiveContainer,
} from 'recharts';

const data = [
   {
      name: 'Page A',
      uv: 4000,
      pv: 2400,
      amt: 2400,
   },
   {
      name: 'Page B',
      uv: 3000,
      pv: 1398,
      amt: 2210,
   },
   {
      name: 'Page C',
      uv: 2000,
      pv: 9800,
      amt: 2290,
   },
   {
      name: 'Page D',
      uv: 2780,
      pv: 3908,
      amt: 2000,
   },
   {
      name: 'Page E',
      uv: 1890,
      pv: 4800,
      amt: 2181,
   },
   {
      name: 'Page F',
      uv: 2390,
      pv: 3800,
      amt: 2500,
   },
   {
      name: 'Page G',
      uv: 3490,
      pv: 4300,
      amt: 2100,
   },
];

export default function Chart({ dataProvider }: { dataProvider: IChartDataProvider}) {
   const title = dataProvider.subChartTitle ? (
      <div>{dataProvider.chartTitle} - {dataProvider.subChartTitle}</div>
   ) : (
      <div>{dataProvider.chartTitle}</div>
   );

   return (
      <>
         <div className="container inline">
            <button
               className="btn btn-light btn-sm material-icons"
               type="button"
               onClick={dataProvider.previous}
               data-toggle="tooltip"
               data-placement="bottom"
               title="Previous"
            >
               navigate_before
            </button>
            <span className="ml-auto">{title}</span>
            <button
               className="btn btn-light btn-sm ml-auto material-icons"
               type="button"
               onClick={dataProvider.next}
               data-toggle="tooltip"
               data-placement="bottom"
               title="Next"
            >
               navigate_next
            </button>
         </div>
         <div
            style={{
               width: '100%',
               minHeight: '500px',
               maxHeight: '500px',
               marginBottom: '60px',
               height:"500px"
            }}
         >
            <ResponsiveContainer>
               <LineChart
                  data={data}
                  margin={{
                     top: 5,
                     right: 30,
                     left: 20,
                     bottom: 5,
                  }}
               >
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="name" />
                  <YAxis />
                  <Tooltip />
                  <Legend />
                  <Line
                     type="monotone"
                     dataKey="pv"
                     stroke="#8884d8"
                     activeDot={{ r: 8 }}
                  />
                  <Line type="monotone" dataKey="uv" stroke="#82ca9d" />
               </LineChart>
            </ResponsiveContainer>
         </div>
      </>
   );
}

// MyMoney.Web/ClientApp/src/app/shared/components/chart/chart.component.ts
import { Component, Input } from '@angular/core';
import { ISeriesItem } from 'src/app/shared/interfaces';
import { IChartDataProvider } from './chart-data-provider.interface';
import { LegendPosition } from '@swimlane/ngx-charts';

@Component({
   templateUrl: './chart.component.html',
   selector: 'mymoney-chart'
})
export class ChartComponent {
   @Input()
   public dataProvider!: IChartDataProvider;

   @Input()
   public showLegend = true;

   public LegendPosition = LegendPosition;

   public onSelect(item: ISeriesItem): void {
      this.dataProvider.onSelect(item);
   }

   public onNext(): void {
      this.dataProvider.next();
   }

   public onPrevious(): void {
      this.dataProvider.previous();
   }

   public getXAxisTickLabel(val: string): string {
      return '';
   }
}

<div class="container inline">
   <button class="btn btn-light btn-sm material-icons" type="button" (click)="onPrevious()" data-toggle="tooltip" data-placement="bottom"
      title="Previous">navigate_before</button>
   <span class="ml-auto">
      <div *ngIf="dataProvider.subChartTitle">{{ dataProvider.chartTitle }} - {{ dataProvider.subChartTitle }}</div>
      <div *ngIf="!dataProvider.subChartTitle">{{ dataProvider.chartTitle }}</div>
   </span>
   <button class="btn btn-light btn-sm ml-auto material-icons" type="button" (click)="onNext()" data-toggle="tooltip"
      data-placement="bottom" title="Next">navigate_next</button>
</div>
<div style="width: 100%; min-height: 500px; max-height: 500px; margin-bottom: 60px;">
   <ngx-charts-line-chart [scheme]="dataProvider.colorScheme" [legend]="showLegend" [showXAxisLabel]="true" [showYAxisLabel]="true"
      [xAxis]="true" [yAxis]="true" [yAxisLabel]="dataProvider.yAxisLabel" [results]="dataProvider.seriesData | async" [legendTitle]="''"
      (select)="onSelect($event)" [xAxisTickFormatting]="getXAxisTickLabel" [legendPosition]="'below'">
      <ng-template #tooltipTemplate let-model="model">
         {{ (model.id === -1 ? model.series : model.date) }} • {{ model.text }} • £{{ model.amount }}
      </ng-template>
   </ngx-charts-line-chart>
</div>
