// MyMoney.Web/FrontEnd/apps/mymoney-react/src/app/pages/auth/login.tsx
import { Link } from "react-router-dom";
import { ChangeEventHandler, useState } from "react"
import { useDispatch } from 'react-redux';
import { ILoginDto } from '@mymoney/common/api/dtos';
import { login } from "../../state/session-slice";
import Input from "../../components/input";
import { FormControlState } from "../../interfaces/form-conrtol-props";
import { requiredValidator } from "../../functions/validators";
import { useRedirectLoggedInUserToHome } from "../../hooks/user-session";

export default function Login() {
  useRedirectLoggedInUserToHome();

  const [submitted, setSubmitted] = useState<boolean>(false);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [emailState, setEmailState] = useState<FormControlState>({ value: '', errors: null });
  const [passwordState, setPasswordState] = useState<FormControlState>({ value: '', errors: null });
  const dispatch = useDispatch<any>();

  const updateEmail: ChangeEventHandler<HTMLInputElement> = (event) => {
    const email: string = event.target.value;

    const errors = requiredValidator(email, 'Email is required');
    setEmailState({ value: email, errors });
  }

  const updatePassword: ChangeEventHandler<HTMLInputElement> = (event) => {
    const password: string = event.target.value;

    const errors = requiredValidator(password, 'Password is required');
    setPasswordState({ value: password, errors });
  }

  const loginClicked = ()=> {
    setSubmitted(true);

    if (loading) {
      return;
    }

    const emailErrors = requiredValidator(emailState.value, 'Email is required');
    setEmailState({ value: emailState.value, errors: emailErrors });

    const passwordErrors = requiredValidator(passwordState.value, 'Password is required');
    setPasswordState({ value: passwordState.value, errors: passwordErrors });

    if (emailErrors || passwordErrors) {
      return;
    }

    setLoading(true);
    setError(null);

    const credentials: ILoginDto = { email: emailState.value, password: passwordState.value };

    try {
      dispatch(login(credentials)).unwrap();
    } catch (error: any) {
      setError(error.message);
    } finally {
      setLoading(false);
    }
  }

  return (
    <>
      <h2>Login</h2>
      <form>
        <Input
          name="email"
          labelText="Email"
          showErrors={submitted}
          onChange={updateEmail}
          defaultValue={emailState.value}
          errors={emailState.errors}
        />
        <Input
          name="password"
          labelText="Password"
          showErrors={submitted}
          onChange={updatePassword}
          defaultValue={passwordState.value}
          errors={passwordState.errors}
          autoComplete="current-password"
          type="password"
        />
        <div className="form-group">
          <button disabled={loading} type="button" onClick={loginClicked} className="btn btn-primary">
            {loading ? (<span className="spinner-border spinner-border-sm mr-1"></span>) : ''}
            Login
          </button>
          <Link className="btn btn-link" to="/auth/register">Register</Link>
          <Link className="btn btn-link" to="/auth/forgot-password">Forgot password</Link>
        </div>
        {error !== null ? (<div className="alert alert-danger" role="alert">Login failed: {error}</div>) : ''}
      </form>
    </>
  );
}

// MyMoney.Web/FrontEnd/apps/mymoney-angular/src/app/pages/auth/login/login.component.ts
import { Component } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { first } from 'rxjs/operators';
import { ILoginResultDto } from '@mymoney/common/api/dtos';

import { AuthenticationService } from '../../../shared/services';

@Component({
   templateUrl: './login.component.html'
})
export class LoginComponent {

   public loginForm: FormGroup;
   public loginFormControls = {
      email: new FormControl('', [Validators.required]),
      password: new FormControl('', [Validators.required])
   };
   public loading = false;
   public submitted = false;
   public error: string | null = null;

   constructor(
      private readonly authenticationService: AuthenticationService,
      private readonly router: Router
   ) {
      this.loginForm = new FormGroup(this.loginFormControls);
   }

   public onSubmit(): void {
      this.submitted = true;

      if (this.loginForm.invalid) {
         return;
      }

      this.loading = true;
      this.error = null;

      // Login here
      const email = this.loginFormControls.email.value ?? '';
      const password = this.loginFormControls.password.value ?? '';

      this.authenticationService.login(email, password)
         .pipe(first())
         .subscribe(
            (result: ILoginResultDto) => {
               this.loading = false;
               if (result.success) {
                  void this.router.navigate(['/']);
               } else {
                  this.error = result.error;
               }
            },
            error => {
               // Show error
               this.loading = false;
               this.error = 'Unknown error';
            });
   }
}

<h2>Login</h2>
<form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
   <div class="form-group">
      <label for="email">Email</label>
      <input
         type="text"
         name="email"
         formControlName="email"
         class="form-control"
         [ngClass]="{
            'is-invalid': submitted && loginFormControls.email.errors
         }"
      />
      <div
         *ngIf="submitted && loginFormControls.email.errors"
         class="invalid-feedback"
      >
         <div *ngIf="loginFormControls.email.errors['required']">
            Email is required
         </div>
      </div>
   </div>
   <div class="form-group">
      <label for="password">Password</label>
      <input
         type="password"
         name="password"
         formControlName="password"
         class="form-control"
         autocomplete="current-password"
         [ngClass]="{
            'is-invalid': submitted && loginFormControls.password.errors
         }"
      />
      <div
         *ngIf="submitted && loginFormControls.password.errors"
         class="invalid-feedback"
      >
         <div *ngIf="loginFormControls.password.errors['required']">
            Password is required
         </div>
      </div>
   </div>
   <div class="form-group">
      <button [disabled]="loading" class="btn btn-primary">
         <span
            *ngIf="loading"
            class="spinner-border spinner-border-sm mr-1"
         ></span>
         Login
      </button>
      <a routerLink="/auth/register" class="btn btn-link">Register</a>
      <a routerLink="/auth/forgot-password" class="btn btn-link"
         >Forgot password</a
      >
   </div>
   <div *ngIf="error !== null" class="alert alert-danger" role="alert">
      Login failed: {{ error }}
   </div>
</form>
