// MyMoney.Web/FrontEnd/apps/mymoney-angular/src/app/pages/transactions/transactions.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { TransactionService } from '../../shared/services';
import { TransactionViewModel } from '@mymoney/common';
import { Store } from '@ngrx/store';
import { IAppState } from '../../shared/state/app-state';
import { selectTransactions, selectTransactionsDateRange } from '../../shared/state/selectors/transaction.selector';
import { IDateRangeModel } from '../../shared/state/types';
import { toDateString } from '@mymoney/common/functions';

@Component({
   templateUrl: './transactions.component.html',
   styleUrls: ['./transactions.component.scss']
})
export class TransactionsComponent implements OnInit {

   public transactions: TransactionViewModel[] = [];
   public dateRange: IDateRangeModel = { start: new Date(), end: new Date() };
   public dateRangeForm: FormGroup;
   public dateRangeFormControls = {
      start: new FormControl(toDateString(this.dateRange.start), [Validators.required]),
      end: new FormControl(toDateString(this.dateRange.end), [Validators.required])
   }
   public loading = false;
   public submitted = false;

   constructor(
      private readonly transactionService: TransactionService,
      private readonly store: Store<IAppState>
   ) {
      this.dateRangeForm = new FormGroup(this.dateRangeFormControls);
   }

   public ngOnInit(): void {
      this.store
         .select(selectTransactions)
         .subscribe((transactions) => {
            this.transactions = transactions.map(t => new TransactionViewModel(t));
            this.loading = false;
         });

      this.store
         .select(selectTransactionsDateRange)
         .subscribe((dateRange) => {
            this.dateRange = dateRange;

            this.dateRangeFormControls.start.setValue(toDateString(dateRange.start));
            this.dateRangeFormControls.end.setValue(toDateString(dateRange.end));
         });

      this.transactionService.refreshTransactions();
   }

   public get start(): string {
      return this.formatDate(this.dateRange.start);
   }

   public get end(): string {
      return this.formatDate(this.dateRange.end);
   }

   public updateTransactions(): void {

      this.submitted = true;

      if (this.dateRangeForm.invalid) {
         return;
      }

      this.loading = true;

      this.dateRange = { 
         start: new Date(this.dateRangeFormControls.start.value ?? ''),
         end: new Date(this.dateRangeFormControls.end.value ?? '')
      };

      this.transactionService.updateDateRange(this.dateRange);
   }

   public deleteRecurringTransaction(id: number): void {
      if (!confirm(`Delete recurring transaction ${id}?`)) {
         return;
      }

      this.transactionService.deleteRecurringTransaction(id);
   }

   public deleteTransaction(id: number): void {
      if (!confirm(`Delete transaction ${id}?`)) {
         return;
      }

      this.transactionService.deleteTransaction(id);
   }

   private formatDate(date: Date): string {

      const parsedDate = new Date(date);

      const month = parsedDate.getMonth() + 1;

      const day = parsedDate.getDate();

      const monthStr = month < 10 ? '0' + month : month;

      const dayStr = day < 10 ? '0' + day : day;

      return parsedDate.getFullYear() + '-' + monthStr + '-' + dayStr;
   }
}

<h2>Transactions</h2>
<form [formGroup]="dateRangeForm" (ngSubmit)="updateTransactions()">
   <div class="form-inline">
      <div class="input-group mb-3 pr-2">
         <div class="input-group-prepend">
            <span class="input-group-text">Start</span>
         </div>
         <input
            type="date"
            formControlName="start"
            class="form-control"
            (change)="updateTransactions()"
            [ngClass]="{
               'is-invalid': submitted && dateRangeFormControls.start.errors
            }"
         />
         <div
            *ngIf="submitted && dateRangeFormControls.start.errors"
            class="invalid-feedback"
         >
            <div *ngIf="dateRangeFormControls.start.errors['required']">
               Start is required
            </div>
         </div>
      </div>
      <div class="input-group mb-3 pr-2">
         <div class="input-group-prepend">
            <span class="input-group-text">End</span>
         </div>
         <input
            type="date"
            formControlName="end"
            class="form-control"
            (change)="updateTransactions()"
            [ngClass]="{
               'is-invalid': submitted && dateRangeFormControls.end.errors
            }"
         />
         <div
            *ngIf="submitted && dateRangeFormControls.end.errors"
            class="invalid-feedback"
         >
            <div *ngIf="dateRangeFormControls.end.errors['required']">
               End is required
            </div>
         </div>
      </div>
      <div class="input-group mb-3 pr-2 btn-group">
         <button
            [disabled]="loading"
            class="btn btn-primary material-icons"
            data-toggle="tooltip"
            data-placement="bottom"
            title="Refresh transactions"
         >
            <span
               *ngIf="loading"
               class="spinner-border spinner-border-sm"
            ></span>
            <div *ngIf="!loading" class="spin">refresh</div>
         </button>
         <a
            class="btn btn-success material-icons"
            routerLink="./add"
            data-toggle="tooltip"
            data-placement="bottom"
            title="Add new transaction"
         >
            add
         </a>
         <a
            class="btn btn-success material-icons"
            routerLink="./import"
            data-toggle="tooltip"
            data-placement="bottom"
            title="Import transactions from file"
            >upload</a
         >
      </div>
   </div>
</form>
<div class="container-fluid">
   <table class="table">
      <thead>
         <tr>
            <th scope="col">Date</th>
            <th scope="col">Description</th>
            <th scope="col">Amount</th>
            <th scope="col"></th>
         </tr>
      </thead>
      <tbody>
         <tr *ngFor="let transaction of transactions; let i = index">
            <td>{{ transaction.date }}</td>
            <td>{{ transaction.description }}</td>
            <td>{{ transaction.amount }}</td>
            <td class="pull-right">
               <mymoney-basic-transaction-buttons
                  *ngIf="transaction.parentId === null"
                  [transaction]="transaction"
                  (deleteTransaction)="deleteTransaction(transaction.id)"
               ></mymoney-basic-transaction-buttons>
               <mymoney-recurring-transaction-buttons
                  *ngIf="transaction.parentId !== null"
                  [transaction]="transaction"
                  (deleteRecurringTransaction)="
                     deleteRecurringTransaction(transaction.parentId)
                  "
               ></mymoney-recurring-transaction-buttons>
            </td>
         </tr>
      </tbody>
   </table>
</div>

// MyMoney.Web/FrontEnd/apps/mymoney-react/src/app/pages/transactions/index.tsx
import { Link } from 'react-router-dom';
import { ChangeEventHandler, useEffect } from 'react';
import { useDispatch } from 'react-redux';
import { useSelector } from 'react-redux';
import InlineInput from '../../components/inline-input';
import BasicTransactionButtons from '../../components/basic-transaction-buttons';
import { requiredValidator } from '../../functions/validators';
import {
   deleteRecurringTransaction,
   deleteTransaction,
   fetchTransactions,
   refreshTransactions,
   selectTransactionsListState,
   setDataRange,
} from '../../state/transactions';
import { AsyncStatus, ITransactionsState } from '../../state/types';
import RecurringTransactionButtons from '../../components/recurring-transaction-buttons';
import { useValidatedState } from '../../hooks/validation';

export default function Transactions() {
   const tranactionState: ITransactionsState = useSelector(selectTransactionsListState);

   const dateRange = tranactionState.searchParameters.dateRange;
   const [startState, setStartState] = useValidatedState<string>(dateRange.start, [requiredValidator('Start is required')]);
   const [endState, setEndState] = useValidatedState<string>(dateRange.end, [requiredValidator('End is required')]);

   const loading = tranactionState.list.status === AsyncStatus.loading;

   const dispatch = useDispatch<any>();
   useEffect(() => {
      if (loading || (!loading && !tranactionState.searchParameters.refresh)) {
         return;
      }

      dispatch(
         fetchTransactions({
            dateRange: tranactionState.searchParameters.dateRange,
         })
      );
   }, [tranactionState]);

   const updateStart: ChangeEventHandler<HTMLInputElement> = (event) => {
      const start: string = event.target.value;
      setStartState(start);
      dispatch(setDataRange(start, endState.value));
   };

   const updateEnd: ChangeEventHandler<HTMLInputElement> = (event) => {
      const end: string = event.target.value;
      setEndState(end);
      dispatch(setDataRange(startState.value, end));
   };

   const refershClicked = () => {
      if (loading) {
         return;
      }

      const startErrors = setStartState(startState.value);
      const endErrors = setEndState(endState.value);

      if (startErrors || endErrors) {
         return;
      }

      dispatch(refreshTransactions());
   };

   const onDeleteTransactionClicked = (transactionId: number) => {
      dispatch(deleteTransaction({ transactionId }));
   };

   const onDeleteRecurringTransactionClicked = (recurringTransactionId: number | null) => {
      if (!recurringTransactionId) {
         return;
      }

      dispatch(deleteRecurringTransaction({ recurringTransactionId }));
   };

   const rows = [];

   for (const transaction of tranactionState.list.data) {
      rows.push(
         <tr key={transaction.id}>
            <td>{transaction.date}</td>
            <td>{transaction.description}</td>
            <td>{transaction.amount}</td>
            <td className="pull-right">
               {transaction.parentId ? (
                  <RecurringTransactionButtons
                     transaction={transaction}
                     onDeleteClicked={() => onDeleteRecurringTransactionClicked(transaction.parentId)}
                  />
               ) : (
                  <BasicTransactionButtons transaction={transaction} onDeleteClicked={() => onDeleteTransactionClicked(transaction.id)} />
               )}
            </td>
         </tr>
      );
   }

   return (
      <>
         <h2>Transactions</h2>
         <div className="form-inline">
            <InlineInput
               name="start"
               labelText="Start"
               showErrors={true}
               onChange={updateStart}
               defaultValue={startState.value}
               errors={startState.errors}
               type="date"
            />
            <InlineInput
               name="end"
               labelText="End"
               showErrors={true}
               onChange={updateEnd}
               defaultValue={endState.value}
               errors={endState.errors}
               type="date"
            />

            <div className="input-group mb-3 pr-2 btn-group">
               <button
                  disabled={loading}
                  type="button"
                  onClick={refershClicked}
                  className="btn btn-primary material-icons"
                  data-toggle="tooltip"
                  data-placement="bottom"
                  title="Refresh transactions"
               >
                  {loading ? <span className="spinner-border spinner-border-sm"></span> : <div className="spin">refresh</div>}
               </button>
               <Link
                  className="btn btn-success material-icons"
                  to="/transactions/add"
                  data-toggle="tooltip"
                  data-placement="bottom"
                  title="Add new transaction"
               >
                  add
               </Link>
               <Link
                  className="btn btn-success material-icons"
                  to="/transactions/import"
                  data-toggle="tooltip"
                  data-placement="bottom"
                  title="Add new transaction"
               >
                  upload
               </Link>
            </div>
         </div>
         <div className="container-fluid">
            <table className="table">
               <thead>
                  <tr>
                     <th scope="col">Date</th>
                     <th scope="col">Description</th>
                     <th scope="col">Amount</th>
                     <th scope="col"></th>
                  </tr>
               </thead>
               <tbody>{rows}</tbody>
            </table>
         </div>
      </>
   );
}
