// MyMoney.Web/ClientApp/src/app/pages/transactions/transactions.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { TransactionService } from '../../shared/services';
import { DateRangeModel } from '../../shared/interfaces';
import { TransactionViewModel } from '../../shared/classes';

@Component({
   templateUrl: './transactions.component.html'
})
export class TransactionsComponent implements OnInit {

   public transactions: Array<TransactionViewModel> = [];
   public dateRange: DateRangeModel;
   public dateRangeForm: FormGroup;
   public loading: Boolean = false;
   public submitted: Boolean = false;

   constructor(
      private readonly formBuilder: FormBuilder,
      private readonly transactionService: TransactionService,
      private readonly router: Router
   ) {
      this.dateRange = this.defaultDateRange;
   }

   public get defaultDateRange(): DateRangeModel {

      const end: Date = new Date();

      const start: Date = new Date();
      start.setMonth(start.getMonth() - 1);

      return { end, start };
   }

   public ngOnInit(): void {
      this.dateRangeForm = this.formBuilder.group({
         start: [this.start, Validators.required],
         end: [this.end, Validators.required]
      });

      this.fetchTransactions();
   }

   private formatDate(date: Date): string {

      const parsedDate = new Date(date);

      const month = parsedDate.getMonth() + 1;

      const day = parsedDate.getDate();

      const monthStr = month < 10 ? '0' + month : month;

      const dayStr = day < 10 ? '0' + day : day;

      return parsedDate.getFullYear() + '-' + monthStr + '-' + dayStr;
   }

   public get start(): string {
      return this.formatDate(this.dateRange.start);
   }

   public get end(): string {
      return this.formatDate(this.dateRange.end);
   }

   public get f() { return this.dateRangeForm.controls; }

   public delete(id: number): void {

      this.loading = true;

      this.transactionService
         .deleteTransaction(id)
         .subscribe((isDeleted: boolean) => {

            if (isDeleted) {
               this.transactions = this.transactions.filter(v => v.id !== id);
            }

            this.loading = false;
         },
            error => {
               // TODO: Show error
               this.loading = false;
            });
   }

   public onSubmit(): void {
      this.submitted = true;

      if (this.dateRangeForm.invalid) {
         return;
      }

      this.loading = true;

      this.dateRange = { start: this.f.start.value, end: this.f.end.value };

      this.fetchTransactions();
   }

   private fetchTransactions(): void {
      this.transactionService
         .listTransactions(this.dateRange)
         .subscribe(transactions => {

            this.transactions = transactions;
            this.loading = false;
         },
            error => {
               // TODO: Show error
               this.loading = false;
            });
   }
}

<h2>Transactions</h2>
<form [formGroup]="dateRangeForm" (ngSubmit)="updateTransactions()">
   <div class="form-inline">
      <div class="input-group mb-3 pr-2">
         <div class="input-group-prepend">
            <span class="input-group-text">Start</span>
         </div>
         <input type="date" formControlName="start" class="form-control" (change)="updateTransactions()"
            [ngClass]="{ 'is-invalid': submitted && f.start.errors }" />
         <div *ngIf="submitted && f.start.errors" class="invalid-feedback">
            <div *ngIf="f.start.errors.required">Start is required</div>
         </div>
      </div>
      <div class="input-group mb-3 pr-2">
         <div class="input-group-prepend">
            <span class="input-group-text">End</span>
         </div>
         <input type="date" formControlName="end" class="form-control" (change)="updateTransactions()"
            [ngClass]="{ 'is-invalid': submitted && f.end.errors }" />
         <div *ngIf="submitted && f.end.errors" class="invalid-feedback">
            <div *ngIf="f.end.errors.required">End is required</div>
         </div>
      </div>
      <div class="input-group mb-3 pr-2 btn-group">
         <button [disabled]="loading" class="btn btn-primary" data-toggle="tooltip" data-placement="bottom" title="Refresh transactions">
            <span *ngIf="loading" class="spinner-border spinner-border-sm mr-1"></span>
            <div *ngIf="!loading" class="spin">↻</div>
         </button>
         <a class="btn btn-success" routerLink="./add" data-toggle="tooltip" data-placement="bottom" title="Add new transaction">
            <div class="plus"></div>
         </a>
         <a class="btn btn-success" routerLink="./import" data-toggle="tooltip" data-placement="bottom"
            title="Import transactions from file">🗁</a>
      </div>
   </div>
</form>
<div class="container-fluid">
   <table class="table">
      <thead>
         <tr>
            <th scope="col">Date</th>
            <th scope="col">Description</th>
            <th scope="col">Amount</th>
            <th scope="col"></th>
         </tr>
      </thead>
      <tbody>
         <tr *ngFor="let transaction of transactions; let i = index">
            <td>{{transaction.date}}</td>
            <td>{{transaction.description}}</td>
            <td>{{transaction.amount}}</td>
            <td>
               <div *ngIf="transaction.recurringTransactionId !== null" class="btn-group">
                  <a class="btn btn-primary" routerLink="./edit-recurring/{{transaction.recurringTransactionId}}" data-toggle="tooltip"
                     data-placement="bottom" title="Edit recurring transaction {{transaction.recurringTransactionId}}">🖉</a>
                  <button class="btn btn-danger" (click)="deleteRecurringTransaction(transaction.recurringTransactionId)"
                     data-toggle="tooltip" data-placement="bottom"
                     title="Delete recurring transaction {{transaction.recurringTransactionId}}">✕</button>
               </div>
               <div *ngIf="transaction.recurringTransactionId === null" class="btn-group">
                  <a class="btn btn-primary" routerLink="./edit/{{transaction.id}}" data-toggle="tooltip" data-placement="bottom"
                     title=" Edit transaction {{transaction.id}}">🖉</a>
                  <button class="btn btn-danger" (click)="deleteTransaction(transaction.id)" data-toggle="tooltip" data-placement="bottom"
                     title="Delete transaction {{transaction.id}}">✕</button>
               </div>
            </td>
         </tr>
      </tbody>
   </table>
</div>

// MyMoney.Web/FrontEnd/apps/mymoney-react/src/app/pages/transactions/index.tsx
import { Link } from 'react-router-dom';
import { ChangeEventHandler, useEffect, useState } from 'react';
import { useDispatch } from 'react-redux';
import { useSelector } from 'react-redux';
import InlineInput from '../../components/inline-input';
import BasicTransactionButtons from '../../components/basic-transaction-buttons';
import { FormControlState } from '../../interfaces/form-conrtol-props';
import { requiredValidator } from '../../functions/validators';
import {
   deleteRecurringTransaction,
   deleteTransaction,
   fetchTransactions,
   refreshTransactions,
   selectTransactionState,
   setDataRange,
} from '../../state/transactions-slice';
import { AsyncStatus, ITransactionState } from '../../state/types';
import RecurringTransactionButtons from '../../components/recurring-transaction-buttons';

export default function Transactions() {
   const tranactionState: ITransactionState = useSelector(
      selectTransactionState
   );
   const dispatch = useDispatch<any>();
   const [startState, setStartState] = useState<FormControlState<string>>({
      value: '',
      errors: null,
   });
   const [endState, setEndState] = useState<FormControlState<string>>({
      value: '',
      errors: null,
   });

   useEffect(() => {
      setStartState({
         value: tranactionState.searchParameters.dateRange.start,
         errors: null,
      });
      setEndState({
         value: tranactionState.searchParameters.dateRange.end,
         errors: null,
      });
   }, [dispatch]);

   const loading = tranactionState.transactions.status === AsyncStatus.loading;

   useEffect(() => {
      if (loading || (!loading && !tranactionState.searchParameters.refresh)) {
         return;
      }

      dispatch(
         fetchTransactions({
            dateRange: tranactionState.searchParameters.dateRange,
         })
      );
   }, [tranactionState]);

   const updateStart: ChangeEventHandler<HTMLInputElement> = (event) => {
      const start: string = event.target.value;

      const errors = requiredValidator(start, 'Start is required');
      setStartState({ value: start, errors });

      dispatch(setDataRange(start, endState.value));
   };

   const updateEnd: ChangeEventHandler<HTMLInputElement> = (event) => {
      const end: string = event.target.value;

      const errors = requiredValidator(end, 'End is required');
      setEndState({ value: end, errors });

      dispatch(setDataRange(startState.value, end));
   };

   const refershClicked = () => {
      if (loading) {
         return;
      }

      const startErrors = requiredValidator(
         startState.value,
         'Start is required'
      );
      setStartState({ value: startState.value, errors: startErrors });

      const endErrors = requiredValidator(endState.value, 'End is required');
      setEndState({ value: endState.value, errors: endErrors });

      if (startErrors || endErrors) {
         return;
      }

      dispatch(refreshTransactions());
   };

   const onDeleteTransactionClicked = (transactionId: number) => {
      dispatch(deleteTransaction({ transactionId }));
   };

   const onDeleteRecurringTransactionClicked = (
      recurringTransactionId: number | null
   ) => {
      if (!recurringTransactionId) {
         return;
      }

      dispatch(deleteRecurringTransaction({ recurringTransactionId }));
   };

   const rows = [];

   for (const transaction of tranactionState.transactions.data) {
      rows.push(
         <tr key={transaction.id}>
            <td>{transaction.date}</td>
            <td>{transaction.description}</td>
            <td>{transaction.amount}</td>
            <td className="pull-right">
               {transaction.parentId ? (
                  <RecurringTransactionButtons
                     transaction={transaction}
                     onDeleteClicked={() =>
                        onDeleteRecurringTransactionClicked(
                           transaction.parentId
                        )
                     }
                  />
               ) : (
                  <BasicTransactionButtons
                     transaction={transaction}
                     onDeleteClicked={() =>
                        onDeleteTransactionClicked(transaction.id)
                     }
                  />
               )}
            </td>
         </tr>
      );
   }

   return (
      <>
         <h2>Transactions</h2>
         <div className="form-inline">
            <InlineInput
               name="start"
               labelText="Start"
               showErrors={true}
               onChange={updateStart}
               defaultValue={startState.value}
               errors={startState.errors}
               type="date"
            />
            <InlineInput
               name="end"
               labelText="End"
               showErrors={true}
               onChange={updateEnd}
               defaultValue={endState.value}
               errors={endState.errors}
               type="date"
            />

            <div className="input-group mb-3 pr-2 btn-group">
               <button
                  disabled={loading}
                  type="button"
                  onClick={refershClicked}
                  className="btn btn-primary material-icons"
                  data-toggle="tooltip"
                  data-placement="bottom"
                  title="Refresh transactions"
               >
                  {loading ? (
                     <span className="spinner-border spinner-border-sm"></span>
                  ) : (
                     <div className="spin">refresh</div>
                  )}
               </button>
               <Link
                  className="btn btn-success material-icons"
                  to="/transactions/add"
                  data-toggle="tooltip"
                  data-placement="bottom"
                  title="Add new transaction"
               >
                  add
               </Link>
               <Link
                  className="btn btn-success material-icons"
                  to="/transactions/import"
                  data-toggle="tooltip"
                  data-placement="bottom"
                  title="Add new transaction"
               >
                  upload
               </Link>
            </div>
         </div>
         <div className="container-fluid">
            <table className="table">
               <thead>
                  <tr>
                     <th scope="col">Date</th>
                     <th scope="col">Description</th>
                     <th scope="col">Amount</th>
                     <th scope="col"></th>
                  </tr>
               </thead>
               <tbody>{rows}</tbody>
            </table>
         </div>
      </>
   );
}
