// MyMoney.Web/ClientApp/src/app/pages/user/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { CurrentUserService } from '../../../shared/services';
import { toInputDateString } from '../../../shared/functions';
import { filter } from 'rxjs/operators';
import { IUser } from 'src/app/shared/state/types';
import { IBasicResultDto, IUserDto } from 'src/app/shared/api';
import { IAppState } from 'src/app/shared/state/app-state';
import { Store } from '@ngrx/store';
import { SetUserAction } from 'src/app/shared/state/actions';

@Component({
   templateUrl: 'profile.component.html'
})
export class ProfileComponent implements OnInit {
   public profileForm: FormGroup;
   public loading = false;
   public submitted = false;
   public error: string | null = null;

   constructor(
      private readonly formBuilder: FormBuilder,
      private readonly currentUserService: CurrentUserService,
      private readonly store: Store<IAppState>,
   ) {
   }

   public ngOnInit(): void {
      this.profileForm = this.formBuilder.group({
         email: ['', [Validators.required]],
         fullName: ['', [Validators.required]],
         dateOfBirth: [new Date().toISOString().split('T')[0], [Validators.required]],
      });

      this.disableForm();

      this.currentUserService.currentUser()
         .pipe(filter((currentUser: IUser | null) => currentUser !== null))
         .subscribe((currentUser: IUser) => {
            this.f.dateOfBirth.patchValue(toInputDateString(currentUser.dateOfBirth));
            this.f.fullName.patchValue(currentUser.fullName);
            this.f.email.patchValue(currentUser.email);

            this.enableForm();
         });
   }

   public get f() {
      return this.profileForm.controls;
   }

   public onSubmit(): void {
      this.submitted = true;

      if (this.profileForm.invalid) {
         return;
      }

      this.loading = true;
      this.error = null;

      const email: string = this.f.email.value;
      const fullName: string = this.f.fullName.value;
      const dateOfBirth: string = this.f.dateOfBirth.value;

      const newData: IUserDto = {
         email,
         fullName,
         dateOfBirth
      };

      this.currentUserService.updateCurrentUser(newData)
         .subscribe(
            (result: IBasicResultDto) => {

               this.loading = false;

               if (result.success) {

                  // Fix date to match what is expected from the server
                  newData.dateOfBirth = new Date(dateOfBirth).toLocaleDateString('en-GB');

                  this.store.dispatch(new SetUserAction(newData));
               } else {
                  this.error = result.error;
               }
            },
            error => {
               this.error = 'Unknown error';
               this.loading = false;
            });
   }

   private disableForm() {
      this.f.email.disable();
      this.f.fullName.disable();
      this.f.dateOfBirth.disable();
   }

   private enableForm() {
      this.f.email.enable();
      this.f.fullName.enable();
      this.f.dateOfBirth.enable();
   }
}

<h2>Profile</h2>
<form [formGroup]="profileForm" (ngSubmit)="onSubmit()">
   <div class="form-group">
      <label for="email">Email</label>
      <input type="text" formControlName="email" class="form-control" [ngClass]="{ 'is-invalid': submitted && f.email.errors }" />
      <div *ngIf="submitted && f.email.errors" class="invalid-feedback">
         <div *ngIf="f.email.errors.required">Email is required</div>
      </div>
   </div>
   <div class="form-group">
      <label for="fullName">Full name</label>
      <input type="text" formControlName="fullName" class="form-control" [ngClass]="{ 'is-invalid': submitted && f.fullName.errors }" />
      <div *ngIf="submitted && f.fullName.errors" class="invalid-feedback">
         <div *ngIf="f.fullName.errors.required">Full name is required</div>
      </div>
   </div>
   <div class="form-group">
      <label for="dateOfBirth">Data of birth</label>
      <input type="date" formControlName="dateOfBirth" class="form-control"
         [ngClass]="{ 'is-invalid': submitted && f.dateOfBirth.errors }" />
      <div *ngIf="submitted && f.dateOfBirth.errors" class="invalid-feedback">
         <div *ngIf="f.dateOfBirth.errors.required">Date of birth is required</div>
      </div>
   </div>
   <div class="form-group">
      <button [disabled]="loading" class="btn btn-primary">
         <span *ngIf="loading" class="spinner-border spinner-border-sm mr-1"></span>
         Save changes
      </button>
      <a routerLink="/" class="btn btn-link">Cancel</a>
   </div>
   <div *ngIf="error !== null" class="alert alert-danger" role="alert">
      Save failed: {{ error }}
   </div>
</form>

// MyMoney.Web/FrontEnd/apps/mymoney-react/src/app/pages/user/profile.tsx
import { ChangeEventHandler, useEffect, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { IUserDto } from '@mymoney-common/api';
import { selectCurrentUserState, updateUser } from '../../state/session-slice';
import Input from '../../components/input';
import { requiredValidator } from '../../functions/validators';
import { AsyncStatus, IAsyncState } from '../../state/types';
import { toInputDateString } from '@mymoney-common/functions';
import { Link } from 'react-router-dom';
import { useValidatedState } from '../../hooks/validation';

export default function Profile() {
   const userState: IAsyncState<IUserDto | null> = useSelector(selectCurrentUserState);

   const [submitted, setSubmitted] = useState<boolean>(false);
   const [loading, setLoading] = useState<boolean>(false);
   const [error, setError] = useState<string | null>(null);
   const [emailState, setEmailState] = useValidatedState<string>('', [requiredValidator('Email is required')]);
   const [fullNameState, setFullNameState] = useValidatedState<string>('', [requiredValidator('Full name is required')]);
   const [dateOfBirthState, setDateOfBirthState] = useValidatedState<string>('', [requiredValidator('Date of birth is required')]);
   const dispatch = useDispatch<any>();

   useEffect(() => {
      if (userState.status === AsyncStatus.loading || userState.data == null) {
         return;
      }

      setEmailState(userState.data.email);
      setFullNameState(userState.data.fullName);
      setDateOfBirthState(toInputDateString(userState.data.dateOfBirth));
   }, [dispatch, userState.status]);

   const updateEmail: ChangeEventHandler<HTMLInputElement> = (event) => {
      setEmailState(event.target.value);
   };

   const updateFullName: ChangeEventHandler<HTMLInputElement> = (event) => {
      setFullNameState(event.target.value);
   };

   const updateDateOfBirth: ChangeEventHandler<HTMLInputElement> = (event) => {
      setDateOfBirthState(event.target.value);
   };

   const loginClicked = () => {
      setSubmitted(true);

      if (loading) {
         return;
      }

      const emailErrors = setEmailState(emailState.value);
      const fullNameErrors = setFullNameState(fullNameState.value);
      const dateOfBirthErrors = setDateOfBirthState(dateOfBirthState.value);

      if (emailErrors || fullNameErrors || dateOfBirthErrors) {
         return;
      }

      setLoading(true);
      setError(null);

      const user: IUserDto = {
         email: emailState.value,
         fullName: fullNameState.value,
         dateOfBirth: dateOfBirthState.value,
      };

      try {
         dispatch(updateUser(user)).unwrap();
      } catch (error: any) {
         setError(error.message);
      } finally {
         setLoading(false);
      }
   };

   return (
      <>
         <h2>Profile</h2>
         <form>
            <Input
               name="email"
               labelText="Email"
               showErrors={submitted}
               onChange={updateEmail}
               defaultValue={emailState.value}
               errors={emailState.errors}
               type="text"
            />
            <Input
               name="fullName"
               labelText="Full name"
               showErrors={submitted}
               onChange={updateFullName}
               defaultValue={fullNameState.value}
               errors={fullNameState.errors}
               type="text"
            />
            <Input
               name="dateOfBirth"
               labelText="Date Of Birth"
               showErrors={submitted}
               onChange={updateDateOfBirth}
               defaultValue={dateOfBirthState.value}
               errors={dateOfBirthState.errors}
               type="date"
            />
            <div className="form-group">
               <button disabled={loading} type="button" onClick={loginClicked} className="btn btn-primary">
                  {loading ? <span className="spinner-border spinner-border-sm mr-1"></span> : ''}
                  Save changes
               </button>
               <Link className="btn btn-link" to="/">
                  Cancel
               </Link>
            </div>
            {error !== null ? (
               <div className="alert alert-danger" role="alert">
                  Save failed: {error}
               </div>
            ) : (
               ''
            )}
         </form>
      </>
   );
}
