// MyMoney.Web/FrontEnd/apps/mymoney-angular/src/app/shared/components/basic-transaction-buttons/basic-transaction-buttons.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { TransactionViewModel } from '@mymoney/common';

@Component({
   templateUrl: './basic-transaction-buttons.component.html',
   selector: 'mymoney-basic-transaction-buttons'
})
export class BasicTransactionButtonsComponent {

   @Input()
   public transaction!: TransactionViewModel;

   @Output()
   public deleteTransaction: EventEmitter<void> = new EventEmitter<void>();

   public onDeleteTransactionClicked(): void {
      this.deleteTransaction.emit();
   }
}

<div class="btn-group">
   <a
      class="btn btn-primary material-icons"
      routerLink="./edit/{{ transaction.id }}"
      data-toggle="tooltip"
      data-placement="bottom"
      title=" Edit transaction {{ transaction.id }}"
      >edit</a
   >
   <button
      class="btn btn-danger material-icons"
      (click)="onDeleteTransactionClicked()"
      data-toggle="tooltip"
      data-placement="bottom"
      title="Delete transaction {{ transaction.id }}"
   >
      delete
   </button>
</div>

// MyMoney.Web/FrontEnd/apps/mymoney-react/src/app/components/basic-transaction-buttons.tsx
import { ITransactionDto } from "@mymoney/common";
import { Link } from "react-router-dom";

export default function BasicTransactionButtons({ transaction, onDeleteClicked }: { transaction: ITransactionDto, onDeleteClicked: () => void }) {
    return (
        <div className="btn-group">
            <Link
                className="btn btn-primary material-icons"
                to={`/transactions/edit?id=${transaction.id}`}
                data-toggle="tooltip"
                data-placement="bottom"
                title={`Edit transaction ${transaction.id}`}
            >
                edit
            </Link>
            <button
                className="btn btn-danger material-icons"
                onClick={onDeleteClicked}
                data-toggle="tooltip"
                data-placement="bottom"
                title={`Delete transaction ${transaction.id}`}
            >
                delete
            </button>
        </div >
    );
}
