// MyMoney.Web/FrontEnd/apps/mymoney-react/src/app/components/footer.tsx
import packageInfo from '../../../../../package.json';

export default function Footer() {
    return (
        <div className="sticky-bottom footer" style={{ 'float': 'right', 'marginBottom': '15px' }}>
            <span className="text-muted"><i>MyMoney v{packageInfo.version}</i></span>
        </div>
    );
}

// MyMoney.Web/ClientApp/src/app/shared/components/footer/footer.component.ts
import { Component } from '@angular/core';
import packageInfo from '../../../../../package.json';

@Component({
   templateUrl: './footer.component.html',
   selector: 'mymoney-footer'
})
export class FooterComponent {

   public versionString: string = packageInfo.version;
}

<div class="sticky-bottom footer" style="float: right; margin-bottom: 15px;">
   <span class="text-muted"><i>MyMoney v{{versionString}}</i></span>
</div>
