// MyMoney.Web/FrontEnd/React/src/pages/auth/login.tsx
import Link from "next/link";
import { ChangeEventHandler, useState } from "react"

interface LoginState {
  submitted: boolean;
  loading: boolean;
  error: string | null;
  email: string;
  password: string;
}

const initialState: LoginState = {
  submitted: false,
  loading: false,
  error: null,
  email: '',
  password: '',
}

export default function Login() {
  const [state, updateState] = useState<LoginState>(initialState);

  const updateEmail: ChangeEventHandler<HTMLInputElement> = (event) => {
    const email: string = event.target.value;
    updateState({... state, email });
  }

  const updatePassword: ChangeEventHandler<HTMLInputElement> = (event) => {
    const password: string = event.target.value;
    updateState({... state, password });
  }

  function login() {
    updateState({... state, loading: true, error: null });

    
  }

  return (
    <>
      <h2>Login</h2>
      <form>
        <div className="form-group">
          <label htmlFor="email">Email</label>
          <input type="text" name="email" className={`form-control ${state.submitted ? 'is-invalid' : ''}`} defaultValue={state.email} onChange={updateEmail}/>
        </div>
        <div className="form-group">
          <label htmlFor="password">Password</label>
          <input type="password" name="password" className={`form-control ${state.submitted ? 'is-invalid' : ''}`} autoComplete="current-password" defaultValue={state.password} onChange={updatePassword} />
        </div>
        <div className="form-group">
          <button disabled={state.loading} onClick={login} className="btn btn-primary">
            {state.loading ? (<span className="spinner-border spinner-border-sm mr-1"></span>) : ''}
            Login
          </button>
          <Link className="btn btn-link" href="/auth/register">Register</Link>
          <Link className="btn btn-link" href="/auth/forgot-password">Forgot password</Link>
        </div>
        { state.error !== null ? (<div className="alert alert-danger" role="alert">Login failed: {state.error}</div>) : '' }
      </form>
    </>
  );
}

// MyMoney.Web/ClientApp/src/app/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { first } from 'rxjs/operators';

import { AuthenticationService } from '../../shared/services';

@Component({
   templateUrl: './login.component.html'
})
export class LoginComponent implements OnInit {

   public loginForm: FormGroup;
   public loading = false;
   public submitted = false;

   constructor(
      private readonly formBuilder: FormBuilder,
      private readonly authenticationService: AuthenticationService,
      private readonly router: Router
   ) { }

   public ngOnInit(): void {
      this.loginForm = this.formBuilder.group({
         email: ['', Validators.required],
         password: ['', Validators.required]
      });
   }

   public get f() { return this.loginForm.controls; }

   public onSubmit(): void {
      this.submitted = true;

      // stop here if form is invalid
      if (this.loginForm.invalid) {
         return;
      }

      this.loading = true;

      // Login here
      const email = this.f.email.value;
      const password = this.f.password.value;

      this.authenticationService.login(email, password)
         .pipe(first())
         .subscribe(
            success => {
               this.loading = false;
               if (success) {
                  this.router.navigate(['/']);
               } else {
                  console.log('Failed login');
               }
            },
            error => {
               // Show error
               this.loading = false;
            });
   }
}

<h2>Login</h2>
<form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
   <div class="form-group">
      <label for="email">Email</label>
      <input type="text" formControlName="email" class="form-control" [ngClass]="{ 'is-invalid': submitted && f.email.errors }" />
      <div *ngIf="submitted && f.email.errors" class="invalid-feedback">
         <div *ngIf="f.email.errors.required">email is required</div>
      </div>
   </div>
   <div class="form-group">
      <label for="password">Password</label>
      <input type="password" formControlName="password" class="form-control" [ngClass]="{ 'is-invalid': submitted && f.password.errors }" />
      <div *ngIf="submitted && f.password.errors" class="invalid-feedback">
         <div *ngIf="f.password.errors.required">Password is required</div>
      </div>
   </div>
   <div class="form-group">
      <button [disabled]="loading" class="btn btn-primary">
         <span *ngIf="loading" class="spinner-border spinner-border-sm mr-1"></span>
         Login
      </button>
      <a routerLink="/auth/register" class="btn btn-link">Register</a>
   </div>
   <div *ngIf="error !== null" class="alert alert-danger" role="alert">
      Login failed: {{ error }}
   </div>
</form>
