// MyMoney.Web/ClientApp/src/app/pages/budgets/budgets.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';

import { AuthenticationService } from '../../shared/services';
import { BudgetViewModel } from '../../shared/classes';
import { BudgetListResponse, DeleteResponse } from '../../shared/interfaces';

@Component({
   templateUrl: './budgets.component.html'
})
export class BudgetsComponent implements OnInit {

   public budgets: Array<BudgetViewModel> = [];
   public year: Number;
   public month: Number;
   public monthIdForm: FormGroup;
   public loading: Boolean = false;
   public submitted: Boolean = false;

   constructor(
      private readonly formBuilder: FormBuilder,
      private readonly authenticationService: AuthenticationService,
      private readonly router: Router,
      private readonly http: HttpClient
   ) {
      if (!this.authenticationService.isLoggedIn) {
         this.router.navigate(['/login']);
      }

      this.defaultMonth();
   }

   private defaultMonth(): void {

      const today = new Date();

      this.year = today.getFullYear();
      this.month = today.getMonth() + 1;
   }

   public ngOnInit(): void {
      this.monthIdForm = this.formBuilder.group({
         year: [this.year, Validators.required],
         month: [this.month, Validators.required]
      });

      this.fetchBudgets();
   }

   public get f() { return this.monthIdForm.controls; }

   public delete(id: Number): void {

      this.loading = true;

      this.http
         .post<DeleteResponse>(`/Budget/Delete`, { id })
         .subscribe(response => {

            if (response.success) {
               this.budgets = this.budgets.filter(v => v.id !== id);
            }

            this.loading = false;
         },
            error => {
               // TODO: Show error
               this.loading = false;
            });
   }

   public onSubmit(): void {
      this.submitted = true;

      if (this.monthIdForm.invalid || this.f.year.value < 0 || this.f.month.value < 0 || this.f.month.value > 12) {
         return;
      }

      this.year = this.f.year.value;
      this.month = this.f.month.value;

      this.loading = true;

      this.fetchBudgets();
   }

   private fetchBudgets(): void {

      const monthStr = this.month < 10 ? '0' + this.month : this.month;

      this.http
         .post<BudgetListResponse>(`/Budget/List`, { monthId: '' + this.year + monthStr })
         .subscribe(response => {

            this.budgets = response.budgets.map(t => new BudgetViewModel(t));
            this.loading = false;
         },
            error => {
               // TODO: Show error
               this.loading = false;
            });
   }
}

<h2>Budgets</h2>
<form [formGroup]="monthIdForm" (ngSubmit)="updateBudgets()">
   <div class="form-inline">
      <div class="input-group mb-3 pr-2">
         <div class="input-group-prepend">
            <span class="input-group-text">Year</span>
         </div>
         <input type="number" formControlName="year" class="form-control" [ngClass]="{ 'is-invalid': submitted && f.year.errors }"
            (change)="updateBudgets()" />
         <div *ngIf="submitted && f.year.errors" class="invalid-feedback">
            <div *ngIf="f.year.errors.required">Year is required</div>
            <div *ngIf="f.year.errors.min">Year cannot be less than 1980</div>
         </div>
      </div>
      <div class="input-group mb-3 pr-2">
         <div class="input-group-prepend">
            <span class="input-group-text">Month</span>
         </div>
         <input type="number" formControlName="month" class="form-control" [ngClass]="{ 'is-invalid': submitted && f.month.errors }"
            (change)="updateBudgets()" />
         <div *ngIf="submitted && f.month.errors" class="invalid-feedback">
            <div *ngIf="f.month.errors.required">Month is required</div>
            <div *ngIf="f.month.errors.min">Month cannot be less than 1</div>
            <div *ngIf="f.month.errors.max">Month cannot be greater than 12</div>
         </div>
      </div>
      <div class="input-group mb-3 pr-2 btn-group">
         <button [disabled]="loading" class="btn btn-primary material-icons" data-toggle="tooltip" data-placement="bottom"
            title="Refresh budgets">
            <span *ngIf="loading" class="spinner-border spinner-border-sm mr-1"></span>
            <div *ngIf="!loading" class="spin">refresh</div>
         </button>
         <a class="btn btn-success material-icons" routerLink="./add" data-toggle="tooltip" data-placement="bottom" title="Add new budget">
            add
         </a>
      </div>
   </div>
</form>
<div class="container-fluid">
   <table class="table">
      <thead>
         <tr>
            <th scope="col">Name</th>
            <th scope="col">Amount</th>
            <th scope="col">Remaining</th>
            <th scope="col">Notes</th>
            <th scope="col"></th>
         </tr>
      </thead>
      <tbody>
         <tr *ngFor="let budget of budgets; let i = index">
            <td>{{budget.name}}</td>
            <td>{{budget.amount}}</td>
            <td [ngClass]="{ 'text-danger': budget.showWarning }">{{budget.remaining}}</td>
            <td>{{budget.notes}}</td>
            <td class="pull-right">
               <div class="btn-group">
                  <a class="btn btn-primary material-icons" routerLink="./edit/{{budget.id}}" data-toggle="tooltip" data-placement="bottom"
                     title="Edit budget {{budget.id}}">edit</a>
                  <button class="btn btn-danger material-icons" (click)="delete(budget.id)" data-toggle="tooltip" data-placement="bottom"
                     title="Delete budget {{budget.id}}">delete</button>
               </div>
            </td>
         </tr>
      </tbody>
   </table>
</div>

// MyMoney.Web/FrontEnd/apps/mymoney-react/src/app/pages/budgets/index.tsx
import { Link } from 'react-router-dom';
import { ChangeEventHandler, useEffect, useState } from 'react';
import { useDispatch } from 'react-redux';
import { useSelector } from 'react-redux';
import InlineInput from '../../components/inline-input';
import BasicBudgetButtons from '../../components/basic-budget-buttons';
import { FormControlState } from '../../interfaces/form-conrtol-props';
import {
   maxValidator,
   minValidator,
   requiredValidator,
} from '../../functions/validators';
import {
   deleteBudget,
   fetchBudgets,
   refreshBudgets,
   selectBudgetState,
   setSelectedMonth,
} from '../../state/budgets-slice';
import { AsyncStatus, IBudgetState } from '../../state/types';

export default function Budgets() {
   const budgetState: IBudgetState = useSelector(selectBudgetState);
   const dispatch = useDispatch<any>();
   const [yearState, setYearState] = useState<FormControlState<number>>({
      value: new Date().getFullYear(),
      errors: null,
   });
   const [monthState, setMonthState] = useState<FormControlState<number>>({
      value: new Date().getMonth() + 1,
      errors: null,
   });

   useEffect(() => {
      setYearState({
         value: budgetState.searchParameters.year,
         errors: null,
      });

      setMonthState({
         value: budgetState.searchParameters.month,
         errors: null,
      });

      dispatch(refreshBudgets());
   }, [dispatch]);

   const loading = budgetState.budgets.status === AsyncStatus.loading;

   useEffect(() => {
      if (loading || (!loading && !budgetState.searchParameters.refresh)) {
         return;
      }

      dispatch(
         fetchBudgets({
            search: {
               year: budgetState.searchParameters.year,
               month: budgetState.searchParameters.month,
            },
         })
      );
   }, [budgetState]);

   const updateYear: ChangeEventHandler<HTMLInputElement> = (event) => {
      const year: number = Number.parseInt(event.target.value);

      const errors = {
         ...minValidator(year, 1980, 'Year must be greater than or equal to 1'),
      };
      setYearState({ value: year, errors });

      dispatch(setSelectedMonth(year, monthState.value));
   };

   const updateMonth: ChangeEventHandler<HTMLInputElement> = (event) => {
      let month: number = Number.parseInt(event.target.value);

      if (month === 13 && monthState.value === 12) {
         // Loop back to january
         month = 1;
         event.currentTarget.value = '1';
      }

      if (month === 0 && monthState.value === 1) {
         // Loop back to december
         month = 12;
         event.currentTarget.value = '12';
      }

      const errors = {
         ...maxValidator(month, 12, 'Month must be less than or equal to 12'),
         ...minValidator(month, 1, 'Month must be greater than or equal to 1'),
      };
      setMonthState({ value: month, errors });

      dispatch(setSelectedMonth(yearState.value, month));
   };

   const refershClicked = () => {
      if (loading) {
         return;
      }

      const yearErrors = {
         ...minValidator(
            yearState.value,
            1980,
            'Year must be greater than or equal to 1'
         ),
         ...requiredValidator(yearState.value, 'Year is required'),
      };
      setYearState({ value: yearState.value, errors: yearErrors });

      const monthErrors = {
         ...maxValidator(
            monthState.value,
            12,
            'Month must be less than or equal to 12'
         ),
         ...minValidator(
            monthState.value,
            1,
            'Month must be greater than or equal to 1'
         ),
         ...requiredValidator(monthState.value, 'Month is required'),
      };
      setMonthState({ value: monthState.value, errors: monthErrors });

      if (Object.keys(yearErrors).length || Object.keys(monthErrors).length) {
         return;
      }

      dispatch(refreshBudgets());
   };

   const onDeleteBudgetClicked = (budgetId: number) => {
      dispatch(deleteBudget({ budgetId }));
   };

   const rows = [];

   for (const budget of budgetState.budgets.data) {
      rows.push(
         <tr key={budget.id}>
            <td>{budget.name}</td>
            <td>{budget.amount}</td>
            <td className={budget.remaining <= 0 ? 'text-danger' : ''}>
               {budget.remaining}
            </td>
            <td>{budget.notes}</td>
            <td className="pull-right">
               <BasicBudgetButtons
                  budget={budget}
                  onDeleteClicked={() => onDeleteBudgetClicked(budget.id)}
               />
            </td>
         </tr>
      );
   }

   return (
      <>
         <h2>Budgets</h2>
         <div className="form-inline">
            <InlineInput
               name="year"
               labelText="Year"
               showErrors={true}
               onChange={updateYear}
               defaultValue={`${yearState.value}`}
               errors={yearState.errors}
               type="number"
            />
            <InlineInput
               name="month"
               labelText="Month"
               showErrors={true}
               onChange={updateMonth}
               defaultValue={`${monthState.value}`}
               errors={monthState.errors}
               type="number"
            />

            <div className="input-group mb-3 pr-2 btn-group">
               <button
                  disabled={loading}
                  type="button"
                  onClick={refershClicked}
                  className="btn btn-primary material-icons"
                  data-toggle="tooltip"
                  data-placement="bottom"
                  title="Refresh budgets"
               >
                  {loading ? (
                     <span className="spinner-border spinner-border-sm"></span>
                  ) : (
                     <div className="spin">refresh</div>
                  )}
               </button>
               <Link
                  className="btn btn-success material-icons"
                  to="/budgets/add"
                  data-toggle="tooltip"
                  data-placement="bottom"
                  title="Add new budget"
               >
                  add
               </Link>
            </div>
         </div>
         <div className="container-fluid">
            <table className="table">
               <thead>
                  <tr>
                     <th scope="col">Name</th>
                     <th scope="col">Amount</th>
                     <th scope="col">Remaining</th>
                     <th scope="col">Notes</th>
                     <th scope="col"></th>
                  </tr>
               </thead>
               <tbody>{rows}</tbody>
            </table>
         </div>
      </>
   );
}
