// MyMoney.Web/FrontEnd/apps/mymoney-react/src/app/components/recurring-transaction-buttons.tsx
import { ITransactionDto } from "@mymoney/common";
import { Link } from "react-router-dom";

export default function RecurringTransactionButtons({ transaction, onDeleteClicked }: { transaction: ITransactionDto, onDeleteClicked: () => void }) {
    return (
        <div className="btn-group">
            {transaction.id > 0 ? (
                <Link
                    className="btn btn-primary material-icons"
                    to={`/transactions/edit?id=${transaction.id}`}
                    data-toggle="tooltip"
                    data-placement="bottom"
                    title="Edit notes for child transaction"
                >
                    comment
                </Link>
            ) : ''}

            <Link
                className="btn btn-primary material-icons"
                to={`/transactions/edit-recurring?id=${transaction.parentId}`}
                data-toggle="tooltip"
                data-placement="bottom"
                title={`Edit recurring transaction ${transaction.parentId}`}
            >
                edit
            </Link>
            <button
                className="btn btn-danger material-icons"
                onClick={onDeleteClicked}
                data-toggle="tooltip"
                data-placement="bottom"
                title={`Delete recurring transaction ${transaction.parentId}`}
            >
                delete
            </button>
        </div >
    );
}

// MyMoney.Web/ClientApp/src/app/shared/components/recurring-transaction-buttons/recurring-transaction-buttons.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { TransactionViewModel } from '../../classes';

@Component({
   templateUrl: './recurring-transaction-buttons.component.html',
   selector: 'mymoney-recurring-transaction-buttons'
})
export class RecurringTransactionButtonsComponent {

   @Input()
   public transaction!: TransactionViewModel;

   @Output()
   public deleteRecurringTransaction: EventEmitter<void> = new EventEmitter<void>();

   public onDeleteRecurringTransactionClicked(): void {
      this.deleteRecurringTransaction.emit();
   }
}

<div class="btn-group">
   <a class="btn btn-primary material-icons" *ngIf="transaction.id > 0" routerLink="./edit/{{transaction.id}}" data-toggle="tooltip"
      data-placement="bottom" title=" Edit transaction {{transaction.id}}">comment</a>
   <a class="btn btn-primary material-icons" routerLink="./edit-recurring/{{transaction.parentId}}" data-toggle="tooltip"
      data-placement="bottom" title="Edit recurring transaction {{transaction.parentId}}">edit</a>
   <button class="btn btn-danger material-icons" (click)="onDeleteRecurringTransactionClicked()" data-toggle="tooltip"
      data-placement="bottom" title="Delete recurring transaction {{transaction.parentId}}">delete</button>
</div>
