// MyMoney.Web/FrontEnd/apps/mymoney-angular/src/app/pages/auth/login/login.component.ts
import { Component } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { first } from 'rxjs/operators';
import { ILoginResultDto } from '@mymoney-common/api';
import { AuthenticationService } from '../../../shared/services';

@Component({
   templateUrl: './login.component.html'
})
export class LoginComponent {

   public loginForm: FormGroup;
   public loginFormControls = {
      email: new FormControl('', [Validators.required]),
      password: new FormControl('', [Validators.required])
   };
   public loading = false;
   public submitted = false;
   public error: string | null = null;

   constructor(
      private readonly authenticationService: AuthenticationService,
      private readonly router: Router
   ) {
      this.loginForm = new FormGroup(this.loginFormControls);
   }

   public onSubmit(): void {
      this.submitted = true;

      if (this.loginForm.invalid) {
         return;
      }

      this.loading = true;
      this.error = null;

      // Login here
      const email = this.loginFormControls.email.value ?? '';
      const password = this.loginFormControls.password.value ?? '';

      this.authenticationService.login(email, password)
         .pipe(first())
         .subscribe(
            (result: ILoginResultDto) => {
               this.loading = false;
               if (result.success) {
                  void this.router.navigate(['/']);
               } else {
                  this.error = result.error;
               }
            },
            error => {
               // Show error
               this.loading = false;
               this.error = 'Unknown error';
            });
   }
}

<h2>Login</h2>
<form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
   <div class="form-group">
      <label for="email">Email</label>
      <input
         type="text"
         name="email"
         formControlName="email"
         class="form-control"
         [ngClass]="{
            'is-invalid': submitted && loginFormControls.email.errors
         }"
      />
      <div
         *ngIf="submitted && loginFormControls.email.errors"
         class="invalid-feedback"
      >
         <div *ngIf="loginFormControls.email.errors['required']">
            Email is required
         </div>
      </div>
   </div>
   <div class="form-group">
      <label for="password">Password</label>
      <input
         type="password"
         name="password"
         formControlName="password"
         class="form-control"
         autocomplete="current-password"
         [ngClass]="{
            'is-invalid': submitted && loginFormControls.password.errors
         }"
      />
      <div
         *ngIf="submitted && loginFormControls.password.errors"
         class="invalid-feedback"
      >
         <div *ngIf="loginFormControls.password.errors['required']">
            Password is required
         </div>
      </div>
   </div>
   <div class="form-group">
      <button [disabled]="loading" class="btn btn-primary">
         <span
            *ngIf="loading"
            class="spinner-border spinner-border-sm mr-1"
         ></span>
         Login
      </button>
      <a routerLink="/auth/register" class="btn btn-link">Register</a>
      <a routerLink="/auth/forgot-password" class="btn btn-link"
         >Forgot password</a
      >
   </div>
   <div *ngIf="error !== null" class="alert alert-danger" role="alert">
      Login failed: {{ error }}
   </div>
</form>

// MyMoney.Web/FrontEnd/React/src/pages/auth/login.tsx
import Link from "next/link";
import { ChangeEventHandler, useState } from "react"

interface LoginState {
  submitted: boolean;
  loading: boolean;
  error: string | null;
  email: string;
  password: string;
}

const initialState: LoginState = {
  submitted: false,
  loading: false,
  error: null,
  email: '',
  password: '',
}

export default function Login() {
  const [state, updateState] = useState<LoginState>(initialState);

  const updateEmail: ChangeEventHandler<HTMLInputElement> = (event) => {
    const email: string = event.target.value;
    updateState({... state, email });
  }

  const updatePassword: ChangeEventHandler<HTMLInputElement> = (event) => {
    const password: string = event.target.value;
    updateState({... state, password });
  }

  function login() {
    updateState({... state, loading: true, error: null });

    
  }

  return (
    <>
      <h2>Login</h2>
      <form>
        <div className="form-group">
          <label htmlFor="email">Email</label>
          <input type="text" name="email" className={`form-control ${state.submitted ? 'is-invalid' : ''}`} defaultValue={state.email} onChange={updateEmail}/>
        </div>
        <div className="form-group">
          <label htmlFor="password">Password</label>
          <input type="password" name="password" className={`form-control ${state.submitted ? 'is-invalid' : ''}`} autoComplete="current-password" defaultValue={state.password} onChange={updatePassword} />
        </div>
        <div className="form-group">
          <button disabled={state.loading} onClick={login} className="btn btn-primary">
            {state.loading ? (<span className="spinner-border spinner-border-sm mr-1"></span>) : ''}
            Login
          </button>
          <Link className="btn btn-link" href="/auth/register">Register</Link>
          <Link className="btn btn-link" href="/auth/forgot-password">Forgot password</Link>
        </div>
        { state.error !== null ? (<div className="alert alert-danger" role="alert">Login failed: {state.error}</div>) : '' }
      </form>
    </>
  );
}
