// MyMoney.Web/FrontEnd/apps/mymoney-angular/src/app/pages/transactions/transactions.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { TransactionService } from '../../shared/services';
import { TransactionViewModel } from '@mymoney/common';
import { Store } from '@ngrx/store';
import { IAppState } from '../../shared/state/app-state';
import { selectTransactions, selectTransactionsDateRange } from '../../shared/state/selectors/transaction.selector';
import { IDateRangeModel } from '../../shared/state/types';
import { toDateString } from '@mymoney/common/functions';

@Component({
   templateUrl: './transactions.component.html',
   styleUrls: ['./transactions.component.scss']
})
export class TransactionsComponent implements OnInit {

   public transactions: TransactionViewModel[] = [];
   public dateRange: IDateRangeModel = { start: new Date(), end: new Date() };
   public dateRangeForm: FormGroup;
   public dateRangeFormControls = {
      start: new FormControl(toDateString(this.dateRange.start), [Validators.required]),
      end: new FormControl(toDateString(this.dateRange.end), [Validators.required])
   }
   public loading = false;
   public submitted = false;

   constructor(
      private readonly transactionService: TransactionService,
      private readonly store: Store<IAppState>
   ) {
      this.dateRangeForm = new FormGroup(this.dateRangeFormControls);
   }

   public ngOnInit(): void {
      this.store
         .select(selectTransactions)
         .subscribe((transactions) => {
            this.transactions = transactions.map(t => new TransactionViewModel(t));
            this.loading = false;
         });

      this.store
         .select(selectTransactionsDateRange)
         .subscribe((dateRange) => {
            this.dateRange = dateRange;

            this.dateRangeFormControls.start.setValue(toDateString(dateRange.start));
            this.dateRangeFormControls.end.setValue(toDateString(dateRange.end));
         });

      this.transactionService.refreshTransactions();
   }

   public get start(): string {
      return this.formatDate(this.dateRange.start);
   }

   public get end(): string {
      return this.formatDate(this.dateRange.end);
   }

   public updateTransactions(): void {

      this.submitted = true;

      if (this.dateRangeForm.invalid) {
         return;
      }

      this.loading = true;

      this.dateRange = { 
         start: new Date(this.dateRangeFormControls.start.value ?? ''),
         end: new Date(this.dateRangeFormControls.end.value ?? '')
      };

      this.transactionService.updateDateRange(this.dateRange);
   }

   public deleteRecurringTransaction(id: number): void {
      if (!confirm(`Delete recurring transaction ${id}?`)) {
         return;
      }

      this.transactionService.deleteRecurringTransaction(id);
   }

   public deleteTransaction(id: number): void {
      if (!confirm(`Delete transaction ${id}?`)) {
         return;
      }

      this.transactionService.deleteTransaction(id);
   }

   private formatDate(date: Date): string {

      const parsedDate = new Date(date);

      const month = parsedDate.getMonth() + 1;

      const day = parsedDate.getDate();

      const monthStr = month < 10 ? '0' + month : month;

      const dayStr = day < 10 ? '0' + day : day;

      return parsedDate.getFullYear() + '-' + monthStr + '-' + dayStr;
   }
}

<h2>Transactions</h2>
<form [formGroup]="dateRangeForm" (ngSubmit)="updateTransactions()">
   <div class="form-inline">
      <div class="input-group mb-3 pr-2">
         <div class="input-group-prepend">
            <span class="input-group-text">Start</span>
         </div>
         <input
            type="date"
            formControlName="start"
            class="form-control"
            (change)="updateTransactions()"
            [ngClass]="{
               'is-invalid': submitted && dateRangeFormControls.start.errors
            }"
         />
         <div
            *ngIf="submitted && dateRangeFormControls.start.errors"
            class="invalid-feedback"
         >
            <div *ngIf="dateRangeFormControls.start.errors['required']">
               Start is required
            </div>
         </div>
      </div>
      <div class="input-group mb-3 pr-2">
         <div class="input-group-prepend">
            <span class="input-group-text">End</span>
         </div>
         <input
            type="date"
            formControlName="end"
            class="form-control"
            (change)="updateTransactions()"
            [ngClass]="{
               'is-invalid': submitted && dateRangeFormControls.end.errors
            }"
         />
         <div
            *ngIf="submitted && dateRangeFormControls.end.errors"
            class="invalid-feedback"
         >
            <div *ngIf="dateRangeFormControls.end.errors['required']">
               End is required
            </div>
         </div>
      </div>
      <div class="input-group mb-3 pr-2 btn-group">
         <button
            [disabled]="loading"
            class="btn btn-primary material-icons"
            data-toggle="tooltip"
            data-placement="bottom"
            title="Refresh transactions"
         >
            <span
               *ngIf="loading"
               class="spinner-border spinner-border-sm"
            ></span>
            <div *ngIf="!loading" class="spin">refresh</div>
         </button>
         <a
            class="btn btn-success material-icons"
            routerLink="./add"
            data-toggle="tooltip"
            data-placement="bottom"
            title="Add new transaction"
         >
            add
         </a>
         <a
            class="btn btn-success material-icons"
            routerLink="./import"
            data-toggle="tooltip"
            data-placement="bottom"
            title="Import transactions from file"
            >upload</a
         >
      </div>
   </div>
</form>
<div class="container-fluid">
   <table class="table">
      <thead>
         <tr>
            <th scope="col">Date</th>
            <th scope="col">Description</th>
            <th scope="col">Amount</th>
            <th scope="col"></th>
         </tr>
      </thead>
      <tbody>
         <tr *ngFor="let transaction of transactions; let i = index">
            <td>{{ transaction.date }}</td>
            <td>{{ transaction.description }}</td>
            <td>{{ transaction.amount }}</td>
            <td class="pull-right">
               <mymoney-basic-transaction-buttons
                  *ngIf="transaction.parentId === null"
                  [transaction]="transaction"
                  (deleteTransaction)="deleteTransaction(transaction.id)"
               ></mymoney-basic-transaction-buttons>
               <mymoney-recurring-transaction-buttons
                  *ngIf="transaction.parentId !== null"
                  [transaction]="transaction"
                  (deleteRecurringTransaction)="
                     deleteRecurringTransaction(transaction.parentId)
                  "
               ></mymoney-recurring-transaction-buttons>
            </td>
         </tr>
      </tbody>
   </table>
</div>

// MyMoney.Web/FrontEnd/React/src/pages/transactions/index.tsx
import Link from "next/link";
import { ChangeEventHandler, useEffect, useState } from "react"
import { useDispatch } from 'react-redux';
import { ISessionModel } from 'mymoney-common/lib/interfaces';
import { toDateString } from 'mymoney-common/lib/functions';
import { selectCurrentSession } from "@/state/session-slice";
import { useSelector } from 'react-redux';
import InlineInput from "@/components/inline-input";
import BasicTransactionButtons from "@/components/basic-transaction-buttons";
import { FormControlState } from "@/interfaces/form-conrtol-props";
import { requiredValidator } from "@/functions/validators";
import { IFetchTransactionsRequest, fetchTransactions, refreshTransactions, selectTransactionState, setDataRange } from "@/state/transactions-slice";
import { AsyncStatus, ITransactionState } from "@/state/types";
import RecurringTransactionButtons from "@/components/recurring-transaction-buttons copy";

export default function Transactions() {
   const tranactionState: ITransactionState = useSelector(selectTransactionState);
   const session: ISessionModel | null = useSelector(selectCurrentSession);
   const dispatch = useDispatch<any>();
   const [startState, setStartState] = useState<FormControlState>({ value: '', errors: null });
   const [endState, setEndState] = useState<FormControlState>({ value: '', errors: null });

   useEffect(() => {
      setStartState({ value: tranactionState.searchParameters.dateRange.start, errors: null });
      setEndState({ value: tranactionState.searchParameters.dateRange.end, errors: null });
   }, [dispatch]);

   const loading = tranactionState.transactions.status === AsyncStatus.loading;

   useEffect(() => {
      if (!session?.token) {
         return; // User not logged in
      }

      if (loading || (!loading && !tranactionState.searchParameters.refresh)) {
         return;
      }

      const request: IFetchTransactionsRequest = {
         sessionToken: session.token,
         dateRange: tranactionState.searchParameters.dateRange
      }

      dispatch(fetchTransactions(request));
   }, [session?.token, dispatch, tranactionState]);

   const updateStart: ChangeEventHandler<HTMLInputElement> = (event) => {
      const start: string = event.target.value;

      const errors = requiredValidator(start, 'Start is required');
      setStartState({ value: start, errors });

      dispatch(setDataRange(start, endState.value));
   }

   const updateEnd: ChangeEventHandler<HTMLInputElement> = (event) => {
      const end: string = event.target.value;

      const errors = requiredValidator(end, 'End is required');
      setEndState({ value: end, errors });

      dispatch(setDataRange(startState.value, end));
   }

   const refershClicked = () => {
      if (loading) {
         return;
      }

      const startErrors = requiredValidator(startState.value, 'Start is required');
      setStartState({ value: startState.value, errors: startErrors });

      const endErrors = requiredValidator(endState.value, 'End is required');
      setEndState({ value: endState.value, errors: endErrors });

      if (startErrors || endErrors) {
         return;
      }

      dispatch(refreshTransactions());
   }

   const deleteTransaction = (transactionId: number) => {
      // TODO: Delete transaction
   }

   const deleteRecurringTransaction = (recurringTransactionId: number) => {
      // TODO: Delete recurring
   }

   const rows = [];

   for (const transaction of tranactionState.transactions.data) {
      rows.push((
         <tr key={transaction.id}>
            <td>{transaction.date}</td>
            <td>{transaction.description}</td>
            <td>{transaction.amount}</td>
            <td className="pull-right">
               {transaction.parentId ?
                  (
                     <RecurringTransactionButtons transaction={transaction} onDeleteClicked={() => deleteRecurringTransaction(transaction.parentId ?? 0)} />
                  ) : (
                     <BasicTransactionButtons transaction={transaction} onDeleteClicked={() => deleteTransaction(transaction.id)} />
                  )
               }
            </td>
         </tr>
      ));
   }

   return (
      <>
         <h2>Transactions</h2>
         <div className="form-inline">

            <InlineInput
               name="start"
               labelText="Start"
               showErrors={true}
               onChange={updateStart}
               defaultValue={startState.value}
               errors={startState.errors}
               type="date"
            />
            <InlineInput
               name="end"
               labelText="End"
               showErrors={true}
               onChange={updateEnd}
               defaultValue={endState.value}
               errors={endState.errors}
               type="date"
            />

            <div className="input-group mb-3 pr-2 btn-group">
               <button disabled={loading} type="button" onClick={refershClicked} className="btn btn-primary material-icons" data-toggle="tooltip" data-placement="bottom"
                  title="Refresh transactions" >
                  {loading ? (<span className="spinner-border spinner-border-sm"></span>) : (<div className="spin">refresh</div>)}
               </button>
               <Link className="btn btn-success material-icons" href="/transactions/add" data-toggle="tooltip" data-placement="bottom"
                  title="Add new transaction">add</Link>
               <Link className="btn btn-success material-icons" href="/transactions/import" data-toggle="tooltip" data-placement="bottom"
                  title="Add new transaction">upload</Link>
            </div>
         </div>
         <div className="container-fluid">
            <table className="table">
               <thead>
                  <tr>
                     <th scope="col">Date</th>
                     <th scope="col">Description</th>
                     <th scope="col">Amount</th>
                     <th scope="col"></th>
                  </tr>
               </thead>
               <tbody>
                  {rows}
               </tbody >
            </table >
         </div >
      </>
   );
}
